apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-conf
  labels:
    name: grafana-conf
data:
  datasources.yml: |-
    apiVersion: 1

    datasources:
      - name: Prometheus
        version: 1
        type: prometheus
        access: proxy
        url: http://prometheus-service:9090

      - name: Loki
        version: 1        
        type: loki
        access: proxy
        url: http://loki-service:3100
