# Default values for grafana.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: default

replicaCount: 1

image:
  repository: grafana/grafana
port: 3000
deployment:
  selector: grafana-deployment
service:
  type: NodePort
  port: 3000
  targetPort: 3000
  nodePort: 30001

