# Default values for flask.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  imagePullPolicy: Always
  repository: dockerregistry.local:5000/flask-app-devops
  tag: monitoring-2
  containerPort: 5000

service:
  name: flask-app-service
  type: NodePort
  port: 5000
  targetPort: 5000
  protocol: TCP

ingress:
  enabled: true
  className: public
  